import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';
import vm from 'node:vm';
const html=await readFile('public/index.html','utf8');
for(const phrase of ['计算，','触手可及。','力学与智能，','相遇于灵感。','./structural-design/'])assert(html.includes(phrase));
for(const [,path] of html.matchAll(/(?:src|href|srcset)="\.\/([^"#]+)"/g))await stat(`public/${path.split('?')[0]}`);
new vm.Script(await readFile('public/home.js','utf8'));
assert((await stat('public/assets/bracket-hero.webp')).size<250000);
assert((await stat('public/assets/bracket-hero-small.webp')).size<100000);
assert((await stat('public/assets/rotor-hero.webp')).size<150000);
assert(html.includes('data-src="./assets/rotor-hero.webp"'));
assert(html.includes('href="./material-memory/"'));
assert(html.includes('data-src="./assets/denim-memory.svg"'));
const preview=html.slice(html.indexOf('<div class="chapter chapter-third"'),html.indexOf('<span class="wordmark"'));
assert(preview.includes('即将上线'));
assert(!preview.includes('<a '),'Coming-soon chapter must not have a fake link');
assert.equal((html.match(/class="number"/g)||[]).length,3);
assert((await stat('public/assets/denim-memory.svg')).size<30000);
const denim=await readFile('public/material-memory/index.html','utf8');
for(const [,path] of denim.matchAll(/(?:src|href)="(?:\.\/)?([^":#]+\.(?:css|js))"/g))await stat('public/material-memory/'+path);
for(const file of ['app.js','architecture.js','i18n.js','data.js'])new vm.Script(await readFile('public/material-memory/'+file,'utf8'));
const dataContext={window:{}};vm.createContext(dataContext);
vm.runInContext(await readFile('public/material-memory/data.js','utf8'),dataContext);
assert.equal(dataContext.window.DENIM_DEMO.trajectories.length,8);
assert.equal(dataContext.window.DENIM_DEMO.summary.denim_parameters,918);
assert.equal(dataContext.window.DENIM_DEMO.summary.test.denrm.rmse_mpa,1.135945200920105);
assert(denim.includes('languageToggle')&&denim.includes('architecture.js'));
assert((await readFile('public/home.css','utf8')).includes('overscroll-behavior:none'));
console.log('Homepage copy, links, assets, syntax and image budgets PASS');
assert(html.indexOf('<footer>')<html.indexOf('</section>'),'Footer must stay inside the final scene');
const script=await readFile('public/home.js','utf8');
const boundary=script.match(/function outward\(dy\)\{[^\n]+\}/)[0];
const root={scrollTop:0,clientHeight:800,scrollHeight:1600};
const context={document:{scrollingElement:root}};vm.createContext(context);vm.runInContext(boundary,context);
assert(vm.runInContext('outward(-1)',context));assert(!vm.runInContext('outward(1)',context));
root.scrollTop=400;assert(!vm.runInContext('outward(-1)||outward(1)',context));
root.scrollTop=800;assert(vm.runInContext('outward(1)',context));assert(!vm.runInContext('outward(-1)',context));
console.log('Top / middle / bottom scroll-boundary checks PASS');
