import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';
import vm from 'node:vm';
const html=await readFile('public/index.html','utf8');
for(const phrase of ['计算，','触手可及。','力学与智能，','相遇于灵感。','./structural-design/'])assert(html.includes(phrase));
for(const [,path] of html.matchAll(/(?:src|href|srcset)="\.\/([^"#]+)"/g))await stat(`public/${path.split('?')[0]}`);
new vm.Script(await readFile('public/home.js','utf8'));
assert((await stat('public/assets/bracket-hero.webp')).size<250000);
assert((await stat('public/assets/bracket-hero-small.webp')).size<100000);
assert((await stat('public/assets/rotor-hero.webp')).size<150000);
assert(html.includes('data-src="./assets/rotor-hero.webp"'));
assert((await readFile('public/home.css','utf8')).includes('overscroll-behavior:none'));
console.log('Homepage copy, links, assets, syntax and image budgets PASS');
assert(html.indexOf('<footer>')<html.indexOf('</section>'),'Footer must stay inside the final scene');
const script=await readFile('public/home.js','utf8');
const boundary=script.match(/function outward\(dy\)\{[^\n]+\}/)[0];
const root={scrollTop:0,clientHeight:800,scrollHeight:1600};
const context={document:{scrollingElement:root}};vm.createContext(context);vm.runInContext(boundary,context);
assert(vm.runInContext('outward(-1)',context));assert(!vm.runInContext('outward(1)',context));
root.scrollTop=400;assert(!vm.runInContext('outward(-1)||outward(1)',context));
root.scrollTop=800;assert(vm.runInContext('outward(1)',context));assert(!vm.runInContext('outward(-1)',context));
console.log('Top / middle / bottom scroll-boundary checks PASS');
