const {chromium}=require('playwright');
const {resolve}=require('node:path');
const {pathToFileURL}=require('node:url');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try{
  const context=await browser.newContext({offline:true,permissions:['clipboard-read','clipboard-write'],viewport:{width:1280,height:900}});
  const page=await context.newPage();
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pathToFileURL(resolve('public/learn/AgentFEM-learning-offline.html')).href);
  const menu=page.locator('.download-menu');
  assert.equal(await menu.locator('.download-options a').count(),3);
  await menu.locator('summary').click();
  assert.equal(await menu.getAttribute('open'),'');
  await page.screenshot({path:'/private/tmp/agentfem-download-menu.png'});
  await page.keyboard.press('Escape');
  assert.equal(await menu.getAttribute('open'),null);
  await menu.locator('summary').click();
  await page.locator('h1').click();
  assert.equal(await menu.getAttribute('open'),null);
  await page.setViewportSize({width:390,height:844});
  await menu.locator('summary').click();
  const box=await menu.locator('.download-options').boundingBox();
  assert(box.x>=0&&box.x+box.width<=390);
  await page.screenshot({path:'/private/tmp/agentfem-download-mobile.png'});
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:1280,height:900});
  await page.locator('#beam').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>Array.from(document.images).every(i=>i.complete&&i.naturalWidth>0));
  const expected=await page.locator('#prompt-beam').textContent();
  await page.locator('[data-copy="prompt-beam"]').click();
  await page.waitForFunction(()=>document.querySelector('[data-copy="prompt-beam"]').textContent==='已复制');
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),expected);
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:undefined,configurable:true}));
  const follow=await page.locator('#follow-beam').textContent();
  await page.locator('[data-copy="follow-beam"]').click();
  await page.waitForFunction(()=>document.querySelector('[data-copy="follow-beam"]').textContent==='已复制');
  await page.evaluate(()=>{const t=document.createElement('textarea');t.id='paste-check';document.body.append(t);t.focus();});
  await page.keyboard.press(process.platform==='darwin'?'Meta+V':'Control+V');
  assert.equal(await page.locator('#paste-check').inputValue(),follow);
  await page.evaluate(()=>{document.execCommand=()=>false;});
  await page.locator('[data-copy="prompt-beam"]').click();
  assert.equal(await page.evaluate(()=>getSelection().toString()),expected);
  assert.match(await page.locator('#copy-status').textContent(),/Ctrl\+C/);
  assert.deepEqual(errors,[]);
  console.log('Offline file: images, modern clipboard, legacy copy/paste and manual fallback PASS');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
